pub mod cli_app;
pub mod core;
pub mod db;
pub mod github;
pub mod models;
pub mod service;
pub mod sync;
pub mod tui_app;

/// Returns the default SQLite database URL, honouring XDG conventions.
///
/// Resolution order:
/// 1. `PR_TRACKER_DB` environment variable (explicit override)
/// 2. `$XDG_DATA_HOME/pr-tracker-rust/db.sqlite3`
/// 3. `$HOME/.local/share/pr-tracker-rust/db.sqlite3` (XDG fallback)
/// 4. `./db.sqlite3` (last-resort relative path)
///
/// The systemd user service (generated by the Home Manager module) always sets
/// `PR_TRACKER_DB` to `$XDG_DATA_HOME/pr-tracker-rust/db.sqlite3`, so cases 2
/// and 3 ensure the CLI uses the same file even when the variable is not set.
pub fn default_db_path() -> String {
    if let Ok(explicit) = std::env::var("PR_TRACKER_DB") {
        return explicit;
    }

    let data_home = std::env::var("XDG_DATA_HOME")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| {
            std::env::var("HOME")
                .ok()
                .map(|home| format!("{home}/.local/share"))
        });

    match data_home {
        Some(base) => format!("sqlite://{base}/pr-tracker-rust/db.sqlite3"),
        None => "sqlite://./db.sqlite3".to_string(),
    }
}
